# 18BCE101
## Practical 6
## Aim:
Performing SVD for a matrix

In [2]:
import numpy as np
 
#Creating a matrix A
A = np.array([[1, 0, 0, 1, 0, 0, 0, 0, 0], 
[1, 0, 1, 0, 0, 0, 0, 0, 0 ],
[1, 1, 0, 0, 0, 0, 0, 0, 0 ],
[0, 1, 1, 0, 1, 0, 0, 0, 0 ],
[0, 1, 1, 2, 0, 0, 0, 0, 0 ],
[0, 1, 0, 0, 1, 0, 0, 0, 0 ],
[0, 1, 0, 0, 1, 0, 0, 0, 0] ,
[0, 0, 1, 1, 0, 0, 0, 0, 0] ,
[0, 1, 0, 0, 0, 0, 0, 0, 1] ,
[0, 0, 0, 0, 0, 1, 1, 1, 0] ,
[0, 0, 0, 0, 0, 0, 1, 1, 1] ,
[0, 0, 0, 0, 0, 0, 0, 1, 1]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A, full_matrices= False)

In [3]:
U.shape

(12, 9)

In [4]:
A.shape

(12, 9)

In [5]:
np.diag(D).shape

(9, 9)

In [6]:
VT.shape

(9, 9)

In [7]:
U

array([[-2.21350778e-01, -1.13179617e-01,  2.88958154e-01,
        -4.14750740e-01, -1.06275121e-01, -3.40983324e-01,
        -5.22657771e-01,  6.04501376e-02,  4.06677509e-01],
       [-1.97645401e-01, -7.20877788e-02,  1.35039639e-01,
        -5.52239584e-01,  2.81768939e-01,  4.95878011e-01,
         7.04234412e-02,  9.94003721e-03,  1.08930266e-01],
       [-2.40470226e-01,  4.31519521e-02, -1.64429079e-01,
        -5.94961818e-01, -1.06755285e-01, -2.54955130e-01,
         3.02240236e-01, -6.23280150e-02, -4.92444364e-01],
       [-4.03598863e-01,  5.70702584e-02, -3.37803538e-01,
         9.91137295e-02,  3.31733718e-01,  3.84831917e-01,
        -2.87217529e-03,  3.90504202e-04, -1.23293479e-02],
       [-6.44481152e-01, -1.67301206e-01,  3.61148151e-01,
         3.33461601e-01, -1.58954979e-01, -2.06522588e-01,
         1.65828575e-01, -3.42720233e-02, -2.70696289e-01],
       [-2.65037470e-01,  1.07159573e-01, -4.25998497e-01,
         7.38121922e-02,  8.03193764e-02, -1.696763

In [8]:
np.diag(D)

array([[3.34088375, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.541701  , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.35394352, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.64453229, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.50483155,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.30638195, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.84590308, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.56013442, 0.        ],


In [9]:
VT

array([[-1.97392802e-01, -6.05990269e-01, -4.62917508e-01,
        -5.42114417e-01, -2.79469108e-01, -3.81521297e-03,
        -1.46314675e-02, -2.41368353e-02, -8.19573680e-02],
       [-5.59135178e-02,  1.65592878e-01, -1.27312062e-01,
        -2.31755229e-01,  1.06774717e-01,  1.92847936e-01,
         4.37874883e-01,  6.15121899e-01,  5.29937072e-01],
       [ 1.10269729e-01, -4.97326494e-01,  2.07605953e-01,
         5.69921445e-01, -5.05449907e-01,  9.81842398e-02,
         1.92955572e-01,  2.52903979e-01,  7.92731465e-02],
       [-9.49785024e-01, -2.86488989e-02,  4.16091951e-02,
         2.67714038e-01,  1.50035433e-01,  1.50814907e-02,
         1.55071875e-02,  1.01990092e-02, -2.45549056e-02],
       [ 4.56785564e-02, -2.06327278e-01,  3.78336233e-01,
        -2.05604711e-01,  3.27194409e-01,  3.94841214e-01,
         3.49485348e-01,  1.49798472e-01, -6.01992995e-01],
       [-7.65935585e-02, -2.56475221e-01,  7.24399642e-01,
        -3.68860901e-01,  3.48130498e-02, -3.001611

In [10]:
ans = U.dot(np.diag(D)).dot(VT)
ans

array([[ 1.00000000e+00, -6.96470142e-16,  2.80278921e-16,
         1.00000000e+00, -5.74929148e-16, -3.50240487e-16,
        -8.07047654e-17, -2.09256829e-16, -7.18332056e-16],
       [ 1.00000000e+00,  2.08135861e-16,  1.00000000e+00,
         2.12512274e-16, -4.83776936e-16,  1.29616923e-16,
        -3.23598209e-16,  3.03127245e-17, -1.57286984e-16],
       [ 1.00000000e+00,  1.00000000e+00,  6.94845814e-16,
        -3.00670616e-16, -2.49793010e-17,  1.82678065e-17,
         4.99379334e-16,  6.47274372e-16,  5.69382619e-16],
       [-4.02706357e-16,  1.00000000e+00,  1.00000000e+00,
         2.90378299e-16,  1.00000000e+00,  1.04279121e-16,
        -3.58907201e-16, -1.06639520e-16, -7.26991768e-17],
       [-6.41930617e-16,  1.00000000e+00,  1.00000000e+00,
         2.00000000e+00, -2.12706803e-16, -2.23708527e-17,
         2.14951235e-17, -4.57621635e-17,  1.75260925e-16],
       [-2.48851108e-16,  1.00000000e+00,  6.42419432e-16,
         5.22020079e-16,  1.00000000e+00,  1.760157